version: '3'

services:
  web:
    image: ghcr.io/reload/drupal-apache-fpm:latest
    ports:
      - '80'
      - '443'
    depends_on:
      - fpm
    volumes:
      - 'webroot:/var/www/'
      - '${HOME}/.local/share/mkcert:/mkcert:ro'
      - '${HOME}/.local/share/dev_certificates:/cert:rw'
    environment:
      VIRTUAL_PROTO: https
      VIRTUAL_HOST: danskkulturarv.docker
      MKCERT_DOMAINS: "danskkulturarv.docker *.danskkulturarv.docker local.docker"
      HTTPS_METHOD: noredirect

  fpm:
    image: ghcr.io/reload/php-fpm:8.2
    user: '${UID:-501}:${GID:-20}'
    ports:
      - '9000'
    depends_on:
      - db
    volumes:
      - 'webroot:/var/www/'
      - './docker/wp-config-docker.php:/var/www/web/wp-config-docker.php'
      - './docker/php-ini.d/99-danskkulturarv.ini:/etc/php/5.6/fpm/pool.d/99-danskkulturarv.ini'
    environment:
      DRUSH_OPTIONS_URI: "https://${COMPOSE_PROJECT_NAME:-gruppeweb}.${DEV_TLD:-docker}"

  wp:
    image: wordpress:cli-2.9-php8.2
    volumes:
      - 'webroot:/var/www/'
      - './docker/wp-config-docker.php:/var/www/web/wp-config-docker.php'
    working_dir: /var/www/web
    depends_on:
      - db
    environment:
      WORDPRESS_DB_PASSWORD: db
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db
    entrypoint: wp

  db:
    image: mariadb:10.3.9
    ports:
      - '3306'
    volumes:
      - 'db-data:/docker-entrypoint-initdb.d'
    depends_on:
      - db-data
    healthcheck:
      test: ["CMD", "lsof", "-i", "tcp:3306"]
    cap_add:
      - SYS_PTRACE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db

  db-data:
    image: eu.gcr.io/reloaddk-data/db-data:danskkulturarv-latest
    volumes:
      - 'db-data:/docker-entrypoint-initdb.d'

volumes:
  webroot:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"
  db-data:
