---
services:
  web:
    image: ghcr.io/reload/https-proxy:drupal
    ports:
      - '80'
      - '443'
    depends_on:
      - php
    volumes:
      - '${PWD}:/var/www/'
      - '${HOME}/.local/share/mkcert:/rootCA:ro'
      - '${HOME}/.local/share/dev_certificates:/cert:rw'
    environment:
      VIRTUAL_PROTO: https
      VIRTUAL_HOST: >-
        ${COMPOSE_PROJECT_NAME:-danskkulturarv}.${DEV_TLD:-docker}
    labels:
      - dev.orbstack.domains=${COMPOSE_PROJECT_NAME:-danskkulturarv}.local
    working_dir: /var/www

  php:
    image: ghcr.io/reload/php-fpm:8.2
    user: '${UID:-501}:${GID:-20}'
    ports:
      - '9000'
    depends_on:
      - db
    volumes:
      - 'webroot:/var/www/'
      - './docker/wp-config-docker.php:/var/www/web/wp-config-docker.php'
      - './docker/php-ini.d/99-danskkulturarv.ini:/etc/php/5.6/fpm/pool.d/99-danskkulturarv.ini'

  wp:
    image: wordpress:cli-2.9-php8.2
    volumes:
      - 'webroot:/var/www/'
      - './docker/wp-config-docker.php:/var/www/web/wp-config-docker.php'
    working_dir: /var/www/web
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_PASSWORD: db
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: db
    entrypoint: wp

  db:
    image: mariadb:10.3
    ports:
      - '3306'
    volumes_from:
      - 'db-data:rw'
    depends_on:
      db-data:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      start_period: 5m
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db

  db-data:
    image: ghcr.io/dr-innovation/danskkulturarv.dk-v3:db-dump

volumes:
  webroot:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}
      o: bind
