web:
  image: reload/drupal-apache-ssl
  ports:
    - '80/tcp'
    - '443/tcp'
  volumes:
    - './web:/var/www/html'
    - './docker/wp-config-docker.php:/var/www/html/wp-config-docker.php'
    - './docker/php-ini.d/99-danskkulturarv.ini:/etc/php/5.6/apache2/conf.d/99-danskkulturarv.ini'
  links:
    - db
  environment:
    # You need to `export UID` in your shell / .profile for this to
    # work. If exported Apache/PHP will run with the UID on your
    # host/mac. I.e. this will avoid files being owned by root when
    # regenerating features from inside Drupal. If not exported
    # Apache/PHP will run with whatever UID the ww-data user was
    # assigned (as before; usually uid 33).
    WWW_DATA_UID: ${UID}

wp:
  image: tatemz/wp-cli
  volumes:
    - './web:/var/www/html'
    - './docker/wp-config-docker.php:/var/www/html/wp-config-docker.php'
  links:
    - db
  environment:
    WORDPRESS_DB_PASSWORD: db
    WORDPRESS_DB_NAME: db
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: db
  entrypoint: wp

db:
  image: mariadb
  ports:
    - '3306/tcp'
  volumes_from:
    - db-data
  environment:
    MYSQL_ROOT_PASSWORD: db
    MYSQL_DATABASE: db
    MYSQL_USER: db
    MYSQL_PASSWORD: db

db-data:
  image: eu.gcr.io/reloaddk-data/db-data:danskkulturarv-latest
